Impatience decreasing is not captured by the exponential discount function, so the Hyperbolic discount function must be used to be compatible with a decreasing discount rate $\rho$.  A simple functional form for the discount function $F(t)$ was suggested by Ainslie (1975):
    
\[
F(t)= \frac{1}{t}
\]

As time passes, the value of $F(t)$ falls. This can be shown with
  
\[
\frac{\partial F(t)}{\partial t}= \frac{-1}{t^2} <0
\]
  
And
  
\[
\frac{\partial^2 F(t)}{\partial t^2}= \frac{2}{t^3} > 0
\] 
  
Which is consistent with decreasing impatience.

Another form was proposed by Mazur (1984):
    
\[
F(t, \rho)= \frac{1}{1 + \rho t}
\]
  
This specification is better in the sense that it states a relationship between the discount function and the discount rate. It can be shown that when as both $t$ and $\rho$ increase, the function value decreases  	
  
\[
\frac{\partial F(t, \rho)}{\partial \rho}= \frac{-t}{(1 + \rho t)^2} < 0 
\]

And 

\[
\frac{\partial F(t, \rho)}{\partial t} = \frac{-\rho}{(1 + \rho t)^2} < 0 
\]
  
With

\[
t, \rho > 0
\]  

Additionally, it is possible to determine more specifically the decreasing impatient in time:
    
\[
\frac{d \rho}{d t} = -\frac{F_{t}(t, \rho)}{F_{\rho}(t, \rho)} =  -\frac{t}{\rho} < 0
\]
  
With

\[
t, \rho > 0
\]  


which is also consistent with decreasing impatience.

Ultimately, Loewenstein \& Prelec (1992) present the general case:
    
\[
F(t)= \frac{1}{(1 + \alpha t)^{\gamma/\alpha}} 
\] 

With

\[
\gamma, \alpha > 0
\]

Where $\alpha$ measures the distance to the exponential discounting and $\gamma$ represents a time preference parameter. This specification is considered to provide the best fit with experimental data (Streich and Levy, 2007).
  
From Figure \ref{fig:hyp} it it is possible to see the differences between the exponential and the hyperbolic function. Starting from $t=0$, the discount function values decreases with time for both specifications. However, exponential discounting implies discount at a constant rate, while hyperbolic discounting implies discount at a (gradually) decreasing rate. This can be seen observing that the hyperbolic function curve is steeper for the first periods (more impatience) and becomes flatter with time (more patience in the future periods), whereas exponential curve's slope decreases smoothly. Actually, after period 7 the Ainslie and Loewenstein functions show greater values than the exponential function. Read (2007) refers to the point where the utilities curves cross each other as *Indifference point / Preference reversal*.   

```{r hyp, echo=FALSE, error=FALSE, fig.align='center', fig.cap="Hyperolic Discount Functions", message=FALSE, warning=FALSE, out.width='75%'}

h_1 <- function(t){
  1/t
}

h_2 <- function(t){
  1/(1 + 2.3*t)
}

h_3 <- function(t){
  1/(1 + 3*t)^(2/3)
}

exp_2 <- function(t){
  0.75^t
}

hyp <- ggplot(data = data.frame(x = 0), mapping = aes(x = x)) +
  
  scale_x_continuous(name = "Time",
                     limits = c(0, 10),
                     breaks = seq(0, 10, 1),
                     labels = number_format(1)) +
  scale_y_continuous(name = "Discounted Value",
                     limits = c(0, 1)) +
  
  stat_function(fun = h_1, aes(linetype = "Ainslie")) +
  stat_function(fun = h_2, aes(linetype = "Mazur")) +
  stat_function(fun = h_3, aes(linetype = "Loewenstein")) +
  stat_function(fun = exp_2, aes(color = "Exponential")) +

  scale_linetype_discrete(name = "")+
  scale_color_discrete(name = "")+
  theme(legend.position = "bottom")

hyp

```

- Ainslie: $\frac{1}{t}$
- Mazur: $\frac{1}{(1+ \rho t)}$ with $\rho = 2.3$
- Loewenstein: $\frac{1}{(1+ \alpha t)^(\frac{\gamma}{\alpha})}$ with $\alpha = 3$ and $\gamma = 2$
- Exponential: $\delta^t$ with $\delta = 0.75$

The hyperbolic Discount function works to show that the discount rate decreases in the long term, but it also requires a sort of consistency over time: longitudinal consistency. Back to our example, an individual could choose \$100 today (instead of \$110 tomorrow) and \$110 in 31 days (instead of \$100 in 30 days). This is captured by the hyperbolic discounting, because in $t=0$ the individual is more patient after 30 days than today. However, if she changes her mind -if she is asked in 30 days and prefers the \$100 in that moment instead to wait one more day to get \$110-, the hyperbolic discount cannot capture this behavior. In other words, hyperbolic discounting can deal with the *delay effect*, but it does not contemplate cases with *longitudinal* time inconsistency.

Regarding to this point, it is necessary to explain in more detail the *Cross-sectional* time consistency -associated with *Date-Independence*- and *longitudinal* time consistency -associated with *Date-Dependence*-. According to Read (2007), date-independence implies that agents not only make consistent plans, but they will also use the same pattern to state plans in every period. This is called cross-sectional time consistency and it would be the case of the exponential discount function. By contrary, with date-dependence agents are allowed to have different discount rates for different periods, but once they stick to a plan, they will not change it. In this case, even though cross-sectional time consistency is violated, longitudinal time consistency holds. *``As has been discussed previously, cross-sectional, but not longitudinal, inconsistencies can occur if the discount rate depends on calendar time rather than temporal distance to the events in question"* (Read, 2012).

This result could be interpreted as following: hyperbolic function allows that the agent becomes more patient with age. In the \$100 vs \$110 example, the future older agent (thirty days from now) will be more patient than the present younger agent, but the hyperbolic function is still in conflict when the agent is more impatient for short term gains than for long term gains at any period.

Therefore, another function is needed to explain the cases when people make a plan, but then they change it.
